# Generated by Django 4.1.7 on 2023-04-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus_table',
            new_name='signup_table',
        ),
    ]
