# Generated by Django 4.1.7 on 2023-04-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_contactus_table_signup_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup_table',
        ),
    ]
